schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EnvironmentInput"
  types:
    EnvironmentInput:
      type: object
      description: Input properties for a new {environment}
      properties:
        versioning:
          title: Enable Versioning
          type: boolean
          default: false
